// Code generated by bcurd. DO NOT EDIT.

package user

import (
	"github.com/happycrud/crud/xsql"
)

var IdOp = xsql.NewFieldOp[int64](Id)

var NameOp = xsql.NewStrFieldOp(Name)

var AgeOp = xsql.NewFieldOp[int64](Age)

var CtimeOp = xsql.NewFieldOp[string](Ctime)

var MtimeOp = xsql.NewFieldOp[string](Mtime)

// And groups predicates with the AND operator between them.
func And(predicates ...xsql.WhereFunc) xsql.WhereFunc {
	return func(s *xsql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	}
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...xsql.WhereFunc) xsql.WhereFunc {
	return func(s *xsql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	}
}

// Not applies the not operator on the given predicate.
func Not(p xsql.WhereFunc) xsql.WhereFunc {
	return func(s *xsql.Selector) {
		p(s.Not())
	}
}
